[package]
name = "flatter"
version = "0.1.0"
authors = ["David Raznick <kindly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yajlish = { version = "0.3.2", features = ["ndjson"] } 
serde_json = "1.0.59"
tempfile = "3.2.0"
itertools = "0.10.1"
csv = "1.1"
clap = "2.33.3"
serde = {version = "1", features = ["derive"] }
