[package]
name = "flatterer"
version = "0.1.0"
authors = ["David Raznick <kindly@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yajlish = { version = "0.3", features = ["ndjson"] } 
serde_json = "1"
tempfile = "3"
itertools = "0.10"
csv = "1"
clap = "2"
serde = {version = "1", features = ["derive"] }

[profile.release]
debug = true

[lib]
name = "flaterer"
path = "src/lib.rs"

[[bin]]
name = "flaterer-cli"
path = "src/main.rs"
